### ISSUE TITLE
섹션2: Github Actions의 event

### ISSUE THREAD

**Issue by yuiseo** [iseo-action/github-actions#3]
## 디렉토리 셋팅
project의 ROOT에 `.github` 디렉토리를 생성하여 github과 관련된 것들을 설정할 수 있다.
workflow를 만들기 위해서는 디렉토리를 다음과 같이 설정해야 한다.
```
📦Project
┗ 📂 .github
    ┗ 📂workflows
       ┗ 📜deoloy.yml
```

## workflow 이름 설정 및 이벤트 트리거 추가
```yml
name: push-workflow1
on: push
```
- name: workflow 이름
- on: github event trigger

## push
```yml
name: push-workflow1
on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hello world
        echo github action
```
- `on` 트리거에 `push`를 작성
> runner에 `|` 을 작성하면 멀티라인 명령이 가능하다!

## pull request
```yml
name: pull-request-workflow
on: pull_request

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hello world
        echo github action
```
- `on` 트리거에 `pull_request`를 작성
- 하지만 해당 코드의 경우 `pull_request`의 `동기화, 오픈, 재오픈`의 경우에도 트리거가 작동한다!
![image](https://github.com/user-attachments/assets/5edf7163-df4a-4849-a328-0297876c2188)
출처: [GitHub Docs - workflow의 event trigger 중 pull request](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request)
- 따라서, 이벤트를 좀 더 세밀하게 지정하기 위해서는 `Activity types`를 지정할 수 있다.
  ```yml
    name: pull-request-workflow
        on: 
          pull_request:
            types: [opened]
  ```

## Reference
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
